### PR TITLE
Add designs to static/designs

### PR DESCRIPTION
**Pull request by jaspercooper**
@Nick-Rivera here are designs for website

- eventually we should write a script to generate these

### CODE REVIEW

**Comment by nfultz** [comment]
I strongly recommend not checking in large numbers of binaries into git, you are going to mess up your repo - can you find a different place to store the rda files in the mean time?

**Comment by graemeblair** [comment]
agreed -- the script should be very simple to write and run during the web site build process (so it uploads the .rda's to netlify but doesn't store on git)

**Comment by jaspercooper** [comment]
Oh yeah that's a much better idea. 

An automated R script would also be better because it will keep things up to date. I've actually already written one for the shiny app. 

Where can I put it so that it gets run on build? @Nick-Rivera you might have an idea here too

**Comment by jaspercooper** [comment]
Here's the script (file path may need to be adjusted). Can you add this to the appropriate place in the build, @Nick-Rivera ?

```r
library(DesignLibrary)

functions <- ls("package:DesignLibrary")
designers <- functions[grepl("_designer\\b",functions)]

for(designer in designers){
	
	the_designer <- get(x = designer)
	design_name <- gsub("_designer\\b","_design",designer)
	assign(x = design_name,value = the_designer())
	file_path <- paste0("static/designs/",design_name,".rda")
	
	save(list = design_name,file = file_path)
	
}
```

**Comment by jaspercooper** [comment]
CI breaking on this, no idea what it means: `The command "./download_packages.sh" exited with 1.`

**Comment by Nick-Rivera** [comment]
The error we're getting is
```
Rendering content/idea/README.Rmd
Quitting from lines 36-52 (README.Rmd) 
Error in declare_citation(description = "A very simple design") : 
  could not find function "declare_citation"
Calls: local ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted
Error in render_page(f) : Failed to render 'content/idea/README.Rmd'
Calls: <Anonymous> -> build_rmds -> render_page
Execution halted
```
Your change didn't cause this, something just changed in the main package.

I'll hook in your script too.

**Comment by graemeblair** [comment]
fixed

**Pull request merged**
